### ISSUE TITLE
Error.. How do i fix this?

### ISSUE THREAD

**Issue by ViniAster** [atalaydenknalbant/autosubscriber-youtube#11]
C:\Users\Vineeth>cd C:\Users\Vineeth\Desktop\autosubscriber-youtube-1.23

C:\Users\Vineeth\Desktop\autosubscriber-youtube-1.23>python Type1_Websites.py
Running Local Version

DevTools listening on ws://127.0.0.1:58985/devtools/browser/55b4272c-b810-4cc5-982d-b1b0887ccb5b

DevTools listening on ws://127.0.0.1:58986/devtools/browser/578ea2f8-2ab7-4e75-9617-e359eae8282a

DevTools listening on ws://127.0.0.1:58987/devtools/browser/a3e1f966-f7f9-49a4-bd90-752ade90886e
[0729/185434.054:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[0729/185434.055:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[0729/185434.056:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
2021-07-29 18:54:56,448 - INFO - ytpals activate button passed
2021-07-29 18:54:56,682 - INFO - ytpals Remaining Videos: 20
2021-07-29 18:54:57,658 - INFO - sonuker activate button passed
2021-07-29 18:54:57,885 - INFO - sonuker Remaining Videos: 20
2021-07-29 18:54:58,548 - INFO - subpals activate button passed
2021-07-29 18:54:58,834 - INFO - subpals Remaining Videos: 20
[0729/185500.190:INFO:CONSOLE(3884)] "LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.", source: https://www.youtube.com/s/desktop/110d331e/jsbin/desktop_polymer.vflset/desktop_polymer.js (3884)
[0729/185500.826:INFO:CONSOLE(0)] "Refused to display 'https://accounts.google.com/' in a frame because it set 'X-Frame-Options' to 'deny'.", source: chrome-error://chromewebdata/ (0)
[0729/185500.978:INFO:CONSOLE(3884)] "LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.", source: https://www.youtube.com/s/desktop/110d331e/jsbin/desktop_polymer.vflset/desktop_polymer.js (3884)
[0729/185501.377:INFO:CONSOLE(0)] "Refused to display 'https://accounts.google.com/' in a frame because it set 'X-Frame-Options' to 'deny'.", source: chrome-error://chromewebdata/ (0)
[0729/185502.091:INFO:CONSOLE(0)] "Refused to display 'https://accounts.google.com/' in a frame because it set 'X-Frame-Options' to 'deny'.", source: chrome-error://chromewebdata/ (0)
[0729/185502.589:INFO:CONSOLE(3884)] "LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.", source: https://www.youtube.com/s/desktop/110d331e/jsbin/desktop_polymer.vflset/desktop_polymer.js (3884)
[0729/185502.609:INFO:CONSOLE(3884)] "LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.", source: https://www.youtube.com/s/desktop/110d331e/jsbin/desktop_polymer.vflset/desktop_polymer.js (3884)
[0729/185504.358:INFO:CONSOLE(3884)] "LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.", source: https://www.youtube.com/s/desktop/110d331e/jsbin/desktop_polymer.vflset/desktop_polymer.js (3884)
[0729/185506.660:INFO:CONSOLE(3884)] "LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.", source: https://www.youtube.com/s/desktop/110d331e/jsbin/desktop_polymer.vflset/desktop_polymer.js (3884)
[0729/185507.417:INFO:CONSOLE(0)] "The resource https://r2---sn-poufvj5cax-cage.googlevideo.com/generate_204?conn2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/watch?v=bQDrsY-jQm8 (0)
[0729/185507.418:INFO:CONSOLE(0)] "The resource https://i.ytimg.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/watch?v=bQDrsY-jQm8 (0)
[0729/185507.420:INFO:CONSOLE(0)] "The resource https://r2---sn-poufvj5cax-cage.googlevideo.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/watch?v=bQDrsY-jQm8 (0)
[0729/185508.300:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185508.300:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185509.573:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185509.573:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185510.949:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185510.949:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185513.283:ERROR:device_event_log_impl.cc(214)] [18:55:13.283] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.
[0729/185513.416:INFO:CONSOLE(0)] "The resource https://r1---sn-poufvj5cax-cage.googlevideo.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/watch?v=oQg-Mu9QkMQ (0)
[0729/185513.417:INFO:CONSOLE(0)] "The resource https://i.ytimg.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/watch?v=oQg-Mu9QkMQ (0)
[0729/185513.418:INFO:CONSOLE(0)] "The resource https://r1---sn-poufvj5cax-cage.googlevideo.com/generate_204?conn2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/watch?v=oQg-Mu9QkMQ (0)
[0729/185513.616:ERROR:device_event_log_impl.cc(214)] [18:55:13.616] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.
[0729/185514.136:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185514.136:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185514.990:ERROR:device_event_log_impl.cc(214)] [18:55:14.990] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.
[0729/185515.474:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185515.474:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185516.665:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185516.665:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185517.983:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185517.983:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185518.652:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185518.652:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185522.248:INFO:CONSOLE(3884)] "LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.", source: https://www.youtube.com/s/desktop/110d331e/jsbin/desktop_polymer.vflset/desktop_polymer.js (3884)
[0729/185522.567:INFO:CONSOLE(3884)] "LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.", source: https://www.youtube.com/s/desktop/110d331e/jsbin/desktop_polymer.vflset/desktop_polymer.js (3884)
[0729/185524.030:INFO:CONSOLE(3884)] "LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.", source: https://www.youtube.com/s/desktop/110d331e/jsbin/desktop_polymer.vflset/desktop_polymer.js (3884)
[0729/185524.673:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185524.674:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185525.486:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185525.486:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185525.672:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185525.672:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0729/185526.081:INFO:CONSOLE(0)] "The resource https://r2---sn-poufvj5cax-cage.googlevideo.com/generate_204?conn2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/watch?v=bQDrsY-jQm8 (0)
[0729/185526.081:INFO:CONSOLE(0)] "The resource https://i.ytimg.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/watch?v=bQDrsY-jQm8 (0)
[0729/185526.083:INFO:CONSOLE(0)] "The resource https://r2---sn-poufvj5cax-cage.googlevideo.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/watch?v=bQDrsY-jQm8 (0)
[0729/185526.906:INFO:CONSOLE(0)] "The resource https://r1---sn-poufvj5cax-cage.googlevideo.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/watch?v=C_-JulrWD7g (0)
[0729/185526.906:INFO:CONSOLE(0)] "The resource https://i.ytimg.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/watch?v=C_-JulrWD7g (0)
[0729/185526.908:INFO:CONSOLE(0)] "The resource https://r1---sn-poufvj5cax-cage.googlevideo.com/generate_204?conn2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/watch?v=C_-JulrWD7g (0)
[0729/185529.057:INFO:CONSOLE(0)] "The resource https://r1---sn-poufvj5cax-cage.googlevideo.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/watch?v=oQg-Mu9QkMQ (0)
[0729/185529.057:INFO:CONSOLE(0)] "The resource https://i.ytimg.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/watch?v=oQg-Mu9QkMQ (0)
[0729/185529.059:INFO:CONSOLE(0)] "The resource https://r1---sn-poufvj5cax-cage.googlevideo.com/generate_204?conn2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://www.youtube.com/watch?v=oQg-Mu9QkMQ (0)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-1.23\selenium_codes\sub4sub_websites_selenium.py", line 418, in ytpals_functions
    type_1_for_loop_like_and_sub(driver, "ytpals", req_dict)
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-1.23\selenium_codes\sub4sub_websites_selenium.py", line 231, in type_1_for_loop_like_and_sub
    ActionChains(driver).move_to_element(like_button).click().perform()
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\action_chains.py", line 80, in perform
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-1.23\selenium_codes\sub4sub_websites_selenium.py", line 378, in sonuker_functions
    type_1_for_loop_like_and_sub(driver, "sonuker", req_dict)
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-1.23\selenium_codes\sub4sub_websites_selenium.py", line 231, in type_1_for_loop_like_and_sub
    ActionChains(driver).move_to_element(like_button).click().perform()
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\action_chains.py", line 80, in perform
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-1.23\selenium_codes\sub4sub_websites_selenium.py", line 330, in subpals_functions
    type_1_for_loop_like_and_sub(driver, "subpals", req_dict)
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-1.23\selenium_codes\sub4sub_websites_selenium.py", line 231, in type_1_for_loop_like_and_sub
    ActionChains(driver).move_to_element(like_button).click().perform()
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\actions\action_builder.py", line 76, in perform
    self.w3c_actions.perform()
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\actions\action_builder.py", line 76, in perform
    self.w3c_actions.perform()
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\actions\action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    self.error_handler.check_response(response)
    self.error_handler.check_response(response)
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable: [object HTMLElement] has no size and location
  (Session info: headless chrome=92.0.4515.107)

    raise exception_class(message, screen, stacktrace)
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable: [object HTMLElement] has no size and location
  (Session info: headless chrome=92.0.4515.107)

selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable: [object HTMLElement] has no size and location
  (Session info: headless chrome=92.0.4515.107)

**Comment by atalaydenknalbant** [comment]
use latest 1.5 version.

**Comment by ViniAster** [comment]
> use latest 1.5 version.

i already did.. but still not working

**Comment by atalaydenknalbant** [comment]
find line 231, in type_1_for_loop_like_and_sub
ActionChains(driver).move_to_element(like_button).click().perform() 
and add driver.save_screenshot('test.png') send that screenshot to me.

**Comment by atalaydenknalbant** [comment]
1 line before ofc

**Comment by ViniAster** [comment]
now it says this..

C:\Users\Vineeth\Desktop\autosubscriber-youtube-1.23>python Type1_Websites.py
Traceback (most recent call last):
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-1.23\Type1_Websites.py", line 1, in <module>
    from selenium_codes import sub4sub_websites_selenium as sws
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-1.23\selenium_codes\sub4sub_websites_selenium.py", line 232
    driver.save_screenshot('test.png')
IndentationError: unexpected unindent

**Comment by atalaydenknalbant** [comment]
you made an indentation mistake which is common with python language, 
make sure you match with indent add it like this 
![image](https://user-images.githubusercontent.com/32653649/127553820-6aea3939-7ee3-417b-b58b-983167f6fb65.png)

**Comment by atalaydenknalbant** [comment]
don't forget to send me that test.png image

**Comment by ViniAster** [comment]
![test](https://user-images.githubusercontent.com/76769197/127558051-f784bdd3-d06e-4814-aada-440cf03bd8f9.png)

Here u go

**Comment by atalaydenknalbant** [comment]
uncomment driver.executescripts() and comment like button and subscribe button with their actionchains. And try this again.
![image](https://user-images.githubusercontent.com/32653649/127561136-f780357a-c038-42e8-a612-e47bcfeba787.png)

**Comment by ViniAster** [comment]
i think it works now
