### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ViniAster** [atalaydenknalbant/autosubscriber-youtube#13]
Started facing this problem again....

Running Local Version

DevTools listening on ws://127.0.0.1:49685/devtools/browser/b3a3018a-3659-4ce9-bfd0-223e69c8bac9
[0824/183222.274:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[0824/183225.030:INFO:CONSOLE(3)] "Uncaught ReferenceError: moment is not defined", source:  (3)
2021-08-24 18:32:39,521 - INFO - Clicked Subscribe Button
[0824/183241.790:INFO:CONSOLE(4163)] "LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.", source: https://www.youtube.com/s/desktop/bd9d1675/jsbin/desktop_polymer.vflset/desktop_polymer.js (4163)
[0824/183242.118:INFO:CONSOLE(0)] "Refused to display 'https://accounts.google.com/' in a frame because it set 'X-Frame-Options' to 'deny'.", source: chrome-error://chromewebdata/ (0)
[0824/183244.232:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0824/183244.232:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0824/183246.063:ERROR:device_event_log_impl.cc(214)] [18:32:46.064] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.
[0824/183246.936:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0824/183246.937:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0824/183250.094:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0824/183250.094:ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
2021-08-24 18:32:52,912 - INFO - google login completed
Traceback (most recent call last):
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-1.23\ytmonster.py", line 40, in <module>
    sws.ytmonster_functions(required_dict)
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-1.23\selenium_codes\sub4sub_websites_selenium.py", line 913, in ytmonster_functions
    for_loop_sub(driver)
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-1.23\selenium_codes\sub4sub_websites_selenium.py", line 840, in for_loop_sub
    driver_6.execute_script(yt_js_sub_button)
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read property 'click' of null
  (Session info: headless chrome=92.0.4515.159)

**Comment by atalaydenknalbant** [comment]
![image](https://user-images.githubusercontent.com/32653649/130669633-4664cb3a-313b-44ee-8cb9-1d1da010ebba.png)
add this and send me a screenshot.
