### ISSUE TITLE
NoSuchElementException: Message: no such element

### ISSUE THREAD

**Issue by Bohosul01** [atalaydenknalbant/autosubscriber-youtube#33]
When I run ytmonster.py it throws an error.

```
Traceback (most recent call last):
  File "ytmonster.py", line 42, in <module>
    sws.ytmonster_functions(required_dict)
  File "C:\Users\asant\Downloads\autosubscriber-youtube-master\autosubscriber-youtube-master\selenium_codes\sub4sub_websites_selenium.py", line 826, in ytmonster_functions
    google_login(driver, req_dict, has_login_btn=False)
  File "C:\Users\asant\Downloads\autosubscriber-youtube-master\autosubscriber-youtube-master\selenium_codes\sub4sub_websites_selenium.py", line 172, in google_login
    driver.find_element(By.CSS_SELECTOR, "#identifierNext > div > button").click()
  File "C:\Users\asant\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 857, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\asant\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "C:\Users\asant\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#identifierNext > div > button"}
  (Session info: headless chrome=103.0.5060.134)
```

**Comment by atalaydenknalbant** [comment]
add this to line 171 and send me the screenshot
driver.save_screenshot("screenshots/g_screenshot.png")

**Comment by atalaydenknalbant** [comment]
update webdriver-manager to 3.8.3

**Comment by Bohosul01** [comment]
Updated webdriver-manager to 3.8.3, but it didn't solve the issue
![g_screenshot](https://user-images.githubusercontent.com/69515506/182030657-185a8435-06e4-41ec-8ec3-1c2ae5961ef6.png)
.

**Comment by Bohosul01** [comment]
I also changed `headless: bool = True` to `headless: bool = False` and it writes my email successfully, but then it crashes.

**Comment by atalaydenknalbant** [comment]
I think some of your web elements are different than any other users I uploaded video demo that explains what you need to pass google login.

https://user-images.githubusercontent.com/32653649/182041948-a79efe1d-8014-484f-a724-2f11bca1d464.mp4

**Comment by Bohosul01** [comment]
I was able to solve it, but now it says that the browser/app is not secure.

![Inicia sesión_ Cuentas de Google - Google Chrome 01_08_2022 13_00_12](https://user-images.githubusercontent.com/69515506/182134612-2f511f03-94ea-44f9-94f0-86abafcc5aa0.png)

Is there any workaround?

**Comment by atalaydenknalbant** [comment]
you need new google account with less security.

**Comment by Bohosul01** [comment]
Ok, I'll try.
