### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ViniAster** [atalaydenknalbant/autosubscriber-youtube#4]
The new release keeps crashing..

**Comment by atalaydenknalbant** [comment]
Try 1.22 and if you encounter an error send me the error code with the specific command line.

**Comment by ViniAster** [comment]
still crashes..

here's the log from heroku:

2021-05-07T12:21:23.069847+00:00 app[worker1.1]: 2021-05-07 12:21:23,069 - INFO - subpals activate button passed 1
2021-05-07T12:21:37.398203+00:00 app[worker1.1]: 2021-05-07 12:21:37,398 - INFO - ytpals activate button passed 1
2021-05-07T12:21:38.121749+00:00 app[worker1.1]: 2021-05-07 12:21:38,121 - INFO - subpals activate button passed 2
2021-05-07T12:21:38.737958+00:00 app[worker1.1]: 2021-05-07 12:21:38,737 - INFO - sonuker activate button passed 1
2021-05-07T12:21:52.417272+00:00 app[worker1.1]: 2021-05-07 12:21:52,417 - INFO - ytpals activate button passed 2
2021-05-07T12:21:53.774080+00:00 app[worker1.1]: 2021-05-07 12:21:53,773 - INFO - sonuker activate button passed 2
2021-05-07T12:21:54.044740+00:00 app[worker1.1]: 2021-05-07 12:21:54,044 - INFO - sonuker Remaining Videos: 19
2021-05-07T12:21:55.360340+00:00 app[worker1.1]: Exception in thread Thread-2:
2021-05-07T12:21:55.360454+00:00 app[worker1.1]: Traceback (most recent call last):
2021-05-07T12:21:55.360489+00:00 app[worker1.1]:   File "/app/.heroku/python/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-05-07T12:21:55.361282+00:00 app[worker1.1]:     self.run()
2021-05-07T12:21:55.361314+00:00 app[worker1.1]:   File "/app/.heroku/python/lib/python3.8/threading.py", line 870, in run
2021-05-07T12:21:55.361975+00:00 app[worker1.1]:     self._target(*self._args, **self._kwargs)
2021-05-07T12:21:55.362007+00:00 app[worker1.1]:   File "/app/selenium_codes/sub4sub_websites_selenium.py", line 340, in sonuker_functions
2021-05-07T12:21:55.362453+00:00 app[worker1.1]:     type_1_for_loop_like_and_sub(driver,
2021-05-07T12:21:55.362484+00:00 app[worker1.1]:   File "/app/selenium_codes/sub4sub_websites_selenium.py", line 153, in type_1_for_loop_like_and_sub
2021-05-07T12:21:55.362818+00:00 app[worker1.1]:     button_subscribe.click()
2021-05-07T12:21:55.362852+00:00 app[worker1.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
2021-05-07T12:21:55.363179+00:00 app[worker1.1]:     self._execute(Command.CLICK_ELEMENT)
2021-05-07T12:21:55.363209+00:00 app[worker1.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
2021-05-07T12:21:55.363773+00:00 app[worker1.1]:     return self._parent.execute(command, params)
2021-05-07T12:21:55.363956+00:00 app[worker1.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
2021-05-07T12:21:55.364602+00:00 app[worker1.1]:     self.error_handler.check_response(response)
2021-05-07T12:21:55.364631+00:00 app[worker1.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
2021-05-07T12:21:55.369073+00:00 app[worker1.1]:     raise exception_class(message, screen, stacktrace)
2021-05-07T12:21:55.369274+00:00 app[worker1.1]: selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <i class="fa fa-youtube-play" aria-hidden="true" rel="noopener noreferrer"></i> is not clickable at point (97, 592). Other element would receive the click: <a href="#" class="at4-count" style="width: 16.6667%;">...</a>
2021-05-07T12:21:55.369276+00:00 app[worker1.1]:   (Session info: headless chrome=90.0.4430.93)
2021-05-07T12:21:55.369301+00:00 app[worker1.1]: 
2021-05-07T12:22:39.971723+00:00 app[worker1.1]: 2021-05-07 12:22:39,971 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0d6838b3a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2aea522a1a1f2aafaf96cb191692d4f9
2021-05-07T12:22:39.972323+00:00 app[worker1.1]: 2021-05-07 12:22:39,972 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0d6820a280>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2aea522a1a1f2aafaf96cb191692d4f9
2021-05-07T12:22:39.973099+00:00 app[worker1.1]: 2021-05-07 12:22:39,972 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0d683a9f40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2aea522a1a1f2aafaf96cb191692d4f9
2021-05-07T12:22:54.260750+00:00 app[worker1.1]: 2021-05-07 12:22:54,260 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0d6a3f3730>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d9f3e97887c401869ddeb3bb41872e01
2021-05-07T12:22:54.261622+00:00 app[worker1.1]: 2021-05-07 12:22:54,261 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0d6a3ba4c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d9f3e97887c401869ddeb3bb41872e01
2021-05-07T12:22:54.262107+00:00 app[worker1.1]: 2021-05-07 12:22:54,261 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0d682146a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d9f3e97887c401869ddeb3bb41872e01
2021-05-07T12:22:54.385031+00:00 heroku[worker1.1]: Process exited with status 0
2021-05-07T12:22:54.455381+00:00 heroku[worker1.1]: State changed from up to crashed

**Comment by atalaydenknalbant** [comment]
I won't suggest running this program using heroku. Try local instead regardless of this I solved your specific error problem

**Comment by ViniAster** [comment]
It dosent run locally also

log:

C:\Users\Vineeth\Desktop\autosubscriber-youtube-master>python Type_1_Websites.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-master\selenium_codes\sub4sub_websites_selenium.py", line 219, in subpals_functions
    driver: webdriver = set_driver_opt(req_dict)
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-master\selenium_codes\sub4sub_websites_selenium.py", line 62, in set_driver_opt
    driver = webdriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"), options=chrome_options)
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\os.py", line 822, in fsdecode
Exception in thread Thread-2:
    filename = fspath(filename)  # Does type-checking of `filename`.
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
TypeError: expected str, bytes or os.PathLike object, not NoneType
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-master\selenium_codes\sub4sub_websites_selenium.py", line 302, in sonuker_functions
Exception in thread Thread-3:
    driver: webdriver = set_driver_opt(req_dict)
Traceback (most recent call last):
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-master\selenium_codes\sub4sub_websites_selenium.py", line 62, in set_driver_opt
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    driver = webdriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"), options=chrome_options)
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.run()
    self.service.start()
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\service.py", line 72, in start
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-master\selenium_codes\sub4sub_websites_selenium.py", line 264, in ytpals_functions
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1360, in _execute_child
    driver: webdriver = set_driver_opt(req_dict)
  File "C:\Users\Vineeth\Desktop\autosubscriber-youtube-master\selenium_codes\sub4sub_websites_selenium.py", line 62, in set_driver_opt
    args = list2cmdline(args)
    driver = webdriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"), options=chrome_options)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 565, in list2cmdline
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    for arg in map(os.fsdecode, seq):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\os.py", line 822, in fsdecode
    self.service.start()
  File "C:\Users\Vineeth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\service.py", line 72, in start
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by ViniAster** [comment]
how do i do that? im the familiar with these stuff.

**Comment by ViniAster** [comment]
its fine..  i figured it out.. i think its working now..

**Comment by atalaydenknalbant** [comment]
https://user-images.githubusercontent.com/32653649/117461510-500cda80-af56-11eb-84ae-f30a7875904a.mp4

**Comment by atalaydenknalbant** [comment]
https://user-images.githubusercontent.com/32653649/117461615-72065d00-af56-11eb-8887-17b328336b94.mp4
